apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw==
  rmq-pass: Z3Vlc3Q=

# app-secret.yml
# Ez egy Secret típusú Kubernetes objektumot hoz létre.
# A Secret-ek arra valók, hogy érzékeny adatokat (pl. jelszavakat, API kulcsokat) tároljanak biztonságos módon.

# name: app-secret: Ez a Secret neve, amire más Kubernetes objektumok hivatkozhatnak.
# type: Opaque: Ez a Secret típusa, ami azt jelenti, hogy tetszőleges adatok tárolhatók benne.
# data:: Itt vannak az érzékeny adatok, Base64 kódolásban:
#       db-pass: dnByb2RicGFzcw== (dekódolva: vprodbpass) - A MySQL adatbázis jelszava.
#       rmq-pass: Z3Vlc3Q== (dekódolva: guest) - A RabbitMQ jelszava.

# Kapcsolat: Ezt a Secret-et használják fel a vprodbdep.yml (adatbázis Deployment)
# és a rmq-dep.yml (RabbitMQ Deployment) fájlok az adatbázis és a RabbitMQ jelszavainak beállításához a konténereik környezeti változóiként.
